capturerActiveRecordingListenPortList: "30000-32000"
capturerArguments: "-port 28000 -webm"
capturerConfigurationPort: 28000
capturerNetworkAdaptorPatern: "CEB"
clusteredInstanceCount: 1
compressorArgumentsWebm: "-y -i {0} -c:v libvpx -threads 3 -f webm {1}"
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceAgent\\\
  bin\\x64\\Debug\\distribution\\compressor\\2016_11_11_11_11_12"
configurationPublishingPeriodInSeconds: 120
enableCapturToFile: true
enableCapturerActiveRecording: true
enableCapturerAutoConfiguration: true
enableCapturerAutoDetectIpId: true
enableCapturerAutoStartup: true
enableCapturerStereoRecording: true
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp"
genesysFailFullDirectoryName: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\\
  SistasVoiceAgent\\bin\\x64\\Debug\\datafiles\\fail"
instanceId: "Agent001"
isAllInOneConfiguration: false
isCompressionEnabled: true
isEncryptionEnabled: true
isFilePurgeEnabled: true
isGenesysActiveRecordingEnabled: false
isSistasConfigurationServerEnabled: true
maxCompressExecutionActorCount: 2
maxCompressExecutionQueueSizePerActor: 11
maxCompressExecutionThreadCountPerActor: 2
maxCompressProcessQueueSize: 10000
maxCompressProcessThreadCount: 4
maxConvertExecutionActorCount: 3
maxConvertExecutionQueueSizePerActor: 100
maxConvertExecutionThreadCountPerActor: 3
maxConvertProcessQueueSize: 3
maxConvertProcessThreadCount: 3
metricsPublishingPeriodInSeconds: 120
minInactiveFilePollingPeriodInMinutes: 1
minMjrConvertLastModifiedTimeElapsedInMinutes: 720
oAuth2ClientSecret: "{cipher}602a9b1d01efb6ac3a55548754779e3a6bfc9906d8f7c1aab6b0a2f368d2df6e9a2817136c8cec39d1bcb17f748871c76034cf516bc67a28bb22d7504ed1e756"
prometheusHostname: "192.168.2.96"
prometheusPort: 28018
reconciliationPeriodInMinutes: 3
restAccessToken: "{cipher}c4d38d140ea28d60218fc0ee1cb67a66c7c638bf52c62456a0ea1e9c5a4c9dea875974920e9a8a91c040a8d6bfb3e993"
saiAnalyzerUri: "{cipher}50d941890a846912d4156065248997f0dd37de5a0c3a715d9eb734c2cf45828fbf573c19ef283a2925ca0b2f2fda2801"
sistasConfigurationServerDownloadPeriodInMinutes: 2
sistasConfigurationServerUrl: "http://192.168.2.70:8888"
uploadSourceFileToAnalitic: ""
uploadType: "rest"
voiceAdminHost: "127.0.0.1"
voiceExplorerUri: "https://localhost:8080"
voiceServerRestHost: "127.0.0.1"
webServerPort: 28339
