capturerActiveRecordingListenPortList: "30000-32000"
capturerArguments: "-port 28000 -webm"
capturerConfigurationPort: 28000
capturerNetworkAdaptorPatern: "CEB"
clusteredInstanceCount: 1
compressorArgumentsWebm: "-y -i {0} -c:v libvpx -threads 3 -f webm {1}"
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceAgent\\\
  bin\\x64\\Debug\\distribution\\compressor\\2016_11_11_11_11_12"
configurationPublishingPeriodInSeconds: 120
enableCapturToFile: true
enableCapturerActiveRecording: true
enableCapturerAutoConfiguration: true
enableCapturerAutoDetectIpId: true
enableCapturerAutoStartup: true
enableCapturerStereoRecording: true
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp"
genesysFailFullDirectoryName: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\\
  SistasVoiceAgent\\bin\\x64\\Debug\\datafiles\\fail"
instanceId: "Agent001"
isAllInOneConfiguration: false
isCompressionEnabled: true
isEncryptionEnabled: true
isFilePurgeEnabled: true
isGenesysActiveRecordingEnabled: false
isSistasConfigurationServerEnabled: true
maxCompressExecutionActorCount: 2
maxCompressExecutionQueueSizePerActor: 11
maxCompressExecutionThreadCountPerActor: 2
maxCompressProcessQueueSize: 10000
maxCompressProcessThreadCount: 4
maxConvertExecutionActorCount: 3
maxConvertExecutionQueueSizePerActor: 100
maxConvertExecutionThreadCountPerActor: 3
maxConvertProcessQueueSize: 3
maxConvertProcessThreadCount: 3
metricsPublishingPeriodInSeconds: 120
minInactiveFilePollingPeriodInMinutes: 1
minMjrConvertLastModifiedTimeElapsedInMinutes: 720
oAuth2ClientSecret: "{cipher}2731eb1ff97e3ab9e7c22c8df4533c3f2b78b1f768c5646dd5af1bc55f91101a036412240f4f716475a04d608fc92c5e2873fa7dd2f91c571d432fba57cc84e8"
prometheusHostname: "192.168.2.96"
prometheusPort: 28018
reconciliationPeriodInMinutes: 3
restAccessToken: "{cipher}5ec920fa0f9178207d3aee1298f30df4a203e5c665c1965c6c7affbc624323aa"
saiAnalyzerUri: "{cipher}cbbce3e56ac4d125da9ccea0ae07297cdd183b00a18473bcc3700951fc47ec9d"
sistasConfigurationServerDownloadPeriodInMinutes: 2
sistasConfigurationServerUrl: "http://192.168.2.70:8888"
uploadSourceFileToAnalitic: ""
uploadSourceFileToAnalytic: false
uploadType: "rest"
voiceAdminHost: "127.0.0.1"
voiceExplorerUri: "https://localhost:8080"
voiceServerRestHost: "127.0.0.1"
webServerPort: 28339
