capturerActiveRecordingListenPortList: "30000-32000"
capturerArguments: "-port 28000 -webm"
capturerConfigurationPort: 28000
capturerNetworkAdaptorPatern: "CEB"
clusteredInstanceCount: 1
compressorArgumentsWebm: "-y -i {0} -c:v libvpx -threads 3 -f webm {1}"
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceAgent\\\
  bin\\x64\\Debug\\distribution\\compressor\\2016_11_11_11_11_12"
configurationPublishingPeriodInSeconds: 1204
enableCapturToFile: true
enableCapturerActiveRecording: true
enableCapturerAutoConfiguration: true
enableCapturerAutoDetectIpId: true
enableCapturerAutoStartup: true
enableCapturerStereoRecording: true
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp"
genesysFailFullDirectoryName: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\\
  SistasVoiceAgent\\bin\\x64\\Debug\\datafiles\\fail"
heartBeatPeriodInSeconds: 3055
instanceId: "Agent001"
isAllInOneConfiguration: false
isCompressionEnabled: true
isEncryptionEnabled: true
isFilePurgeEnabled: true
isGenesysActiveRecordingEnabled: false
isSistasConfigurationServerEnabled: true
isStatisticEnabled: false
maxCompressExecutionActorCount: 2
maxCompressExecutionQueueSizePerActor: 11
maxCompressExecutionThreadCountPerActor: 2
maxCompressProcessQueueSize: 10000
maxCompressProcessThreadCount: 4
maxConvertExecutionActorCount: 3
maxConvertExecutionQueueSizePerActor: 100
maxConvertExecutionThreadCountPerActor: 3
maxConvertProcessQueueSize: 3
maxConvertProcessThreadCount: 3
metricsPublishingPeriodInSeconds: 120
minInactiveFilePollingPeriodInMinutes: 1
minMjrConvertLastModifiedTimeElapsedInMinutes: 720
oAuth2ClientSecret: "{cipher}07c7e274c0fca64d0ecd18bb9d3d6aa942de1b89547c77017e6f13dbadd10ab1161716a3e61474215e0e14ed0caa3e3639401479323fc3432d3519e9c9ccabf3"
prometheusHostname: "192.168.2.96"
prometheusPort: 28018
reconciliationPeriodInMinutes: 3
restAccessToken: "{cipher}b0d59fcd25d5beaff2a4b3d1ef5845a20eda10e8967d31d05548dcc0b7db6c43"
saiAnalyzerUri: "{cipher}eccedf1805d0f536bf5c15b4243ad9d4e18dedf73c2ad938911a5e4fb8072686"
sistasConfigurationServerDownloadPeriodInMinutes: 2
sistasConfigurationServerUrl: "http://192.168.2.70:8888"
uploadSourceFileToAnalitic: ""
uploadSourceFileToAnalytic: false
uploadType: "rest"
voiceAdminHost: "127.0.0.1"
voiceExplorerUri: "https://localhost:80801"
voiceServerRestHost: "127.0.0.1"
webServerPort: 28339
