capturerActiveRecordingListenPortList: "30000-32000"
capturerArguments: "-port 28000 -webm"
capturerConfigurationPort: 28000
capturerNetworkAdaptorPatern: "CEB"
clusteredInstanceCount: 1
compressorArgumentsWebm: "-y -i {0} -c:v libvpx -threads 3 -f webm {1}"
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceAgent\\\
  bin\\x64\\Debug\\distribution\\compressor\\2016_11_11_11_11_12"
configurationPublishingPeriodInSeconds: 120
enableCapturToFile: true
enableCapturerActiveRecording: true
enableCapturerAutoConfiguration: true
enableCapturerAutoDetectIpId: true
enableCapturerAutoStartup: true
enableCapturerStereoRecording: true
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp"
genesysFailFullDirectoryName: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\\
  SistasVoiceAgent\\bin\\x64\\Debug\\datafiles\\fail"
instanceId: "Agent001"
isAllInOneConfiguration: false
isCompressionEnabled: true
isEncryptionEnabled: true
isFilePurgeEnabled: true
isGenesysActiveRecordingEnabled: false
isSistasConfigurationServerEnabled: true
maxCompressExecutionActorCount: 2
maxCompressExecutionQueueSizePerActor: 11
maxCompressExecutionThreadCountPerActor: 2
maxCompressProcessQueueSize: 10000
maxCompressProcessThreadCount: 4
maxConvertExecutionActorCount: 3
maxConvertExecutionQueueSizePerActor: 100
maxConvertExecutionThreadCountPerActor: 3
maxConvertProcessQueueSize: 3
maxConvertProcessThreadCount: 3
metricsPublishingPeriodInSeconds: 120
minInactiveFilePollingPeriodInMinutes: 1
minMjrConvertLastModifiedTimeElapsedInMinutes: 720
oAuth2ClientSecret: "{cipher}48ce2e21e0c066ce2c1ed3a470a884b0e891815b08c1f45f790366b83891a2c024a7e00496b8c04521b519562e505abddcee6686c6ee875ff182a0af09edf24a"
prometheusHostname: "192.168.2.96"
prometheusPort: 28018
reconciliationPeriodInMinutes: 3
restAccessToken: "{cipher}587e78bef31489aeaa31643ab4ea8d7ed7a3ec25cbffa7eb329c7b7bd24a2ff9"
saiAnalyzerUri: "{cipher}268f0c4d335bf72e63bf039937bc756dbd15da4397bcfaffd607cca4c52e0a12"
sistasConfigurationServerDownloadPeriodInMinutes: 2
sistasConfigurationServerUrl: "http://192.168.2.70:8888"
uploadSourceFileToAnalitic: ""
uploadSourceFileToAnalytic: false
uploadType: "rest"
voiceAdminHost: "127.0.0.1"
voiceExplorerUri: "https://localhost:8080"
voiceServerRestHost: "127.0.0.1"
webServerPort: 28339
