capturerActiveRecordingListenPortList: "30000-32000"
capturerArguments: "-port 28000 -webm"
capturerConfigurationPort: 28000
capturerNetworkAdaptorPatern: "CEB"
clusteredInstanceCount: 1
compressorArgumentsWebm: "-y -i {0} -c:v libvpx -threads 3 -f webm {1}"
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceAgent\\\
  bin\\x64\\Debug\\distribution\\compressor\\2016_11_11_11_11_12"
configurationPublishingPeriodInSeconds: 120
enableCapturToFile: true
enableCapturerActiveRecording: true
enableCapturerAutoConfiguration: true
enableCapturerAutoDetectIpId: true
enableCapturerAutoStartup: true
enableCapturerStereoRecording: true
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp"
genesysFailFullDirectoryName: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\\
  SistasVoiceAgent\\bin\\x64\\Debug\\datafiles\\fail"
instanceId: "Agent001"
isAllInOneConfiguration: false
isCompressionEnabled: true
isEncryptionEnabled: true
isFilePurgeEnabled: true
isGenesysActiveRecordingEnabled: false
isSistasConfigurationServerEnabled: true
maxCompressExecutionActorCount: 2
maxCompressExecutionQueueSizePerActor: 11
maxCompressExecutionThreadCountPerActor: 2
maxCompressProcessQueueSize: 10000
maxCompressProcessThreadCount: 4
maxConvertExecutionActorCount: 3
maxConvertExecutionQueueSizePerActor: 100
maxConvertExecutionThreadCountPerActor: 3
maxConvertProcessQueueSize: 3
maxConvertProcessThreadCount: 3
metricsPublishingPeriodInSeconds: 120
minInactiveFilePollingPeriodInMinutes: 1
minMjrConvertLastModifiedTimeElapsedInMinutes: 720
oAuth2ClientSecret: "{cipher}e478228ff350ec9680180de45ebfaf33f15bbe6e19527ea71cc98e5e207ff7e96105d7c7c88dba76ffae4cb1fae0e7d0392a38acee5014d4ea8477a663c2396c"
prometheusHostname: "192.168.2.96"
prometheusPort: 28018
reconciliationPeriodInMinutes: 3
restAccessToken: "{cipher}6ff378f3af119a52c0ee0a2e47b8eb11d5933892092ab8756d6dfe380150a576"
saiAnalyzerUri: "{cipher}e54ab033e8e9d1348b010db354ee19bf94aa38a5ca755c5ca6a3013a0a383a97"
sistasConfigurationServerDownloadPeriodInMinutes: 2
sistasConfigurationServerUrl: "http://192.168.2.70:8888"
uploadSourceFileToAnalitic: ""
uploadSourceFileToAnalytic: false
uploadType: "rest"
voiceAdminHost: "127.0.0.1"
voiceExplorerUri: "https://localhost:8080"
voiceServerRestHost: "127.0.0.1"
webServerPort: 28339
