alcatelAgentActivityMonitorReportIntervalInMinutes: 32
alcatelBipToneGenerationPresenceTimer: 50
alcatelBipToneGenerationSilenceTimer: 0
alcatelBipToneGenerationTonality: 565
alcatelCallConversationLoggerTarget: "TargetTypeDB"
alcatelCallEventDataMappingDefinition: "|1=CorrelatorData|2=GlobalCallId|3=CallingPartyName|4=MessageTimestamp|5=CalledDevice|6=CalledDevice|7=CallingDevice|"
alcatelCallEventLoggerTarget: "TargetTypeDB"
alcatelConfigServerLookupPeriodInMinutes: 1
alcatelCtiExecutionMode: "P"
alcatelMonitoredExtensionRange: "self.In( 1003, 119, 142, 1621, 2008, 2010, 2999,\
  \ 5101, 5200, 5201, 99550, test_agent_2 )"
alcatelTelephonyServerPrimaryHost: "192.168.12.190"
alcatelTelephonyServerStandbyHost: "192.168.12.190"
archiveLocation: "D:\\SistasVoiceData\\Archive"
archivePassword: "asdf<asdf"
archiveType: "local"
cacheClearPeriodInMinutes: 1
clusteredInstanceCount: 1
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceServer\\\
  bin\\x64\\Release\\distribution\\compressor\\2016_11_11_11_11_11"
configurationPublishingPeriodInSeconds: 60
connectionString: "Data Source=localhost; Initial Catalog=sisvoice;User Id=sa; Password=sistas_1"
converterName: "dec729cp_x86.exe"
converterPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceServer\\\
  bin\\x64\\Release\\distribution\\converter\\2016_11_11_11_11_11"
databaseType: "MSSQL"
doNotPassivateAgents: true
domainName: ""
encryptionName: "openssl.exe"
encryptionPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceServer\\\
  bin\\x64\\Release\\distribution\\encryptor\\2016_11_11_11_11_11"
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp\\"
filePurgeFileNameRegex: "^[A-Fa-f0-9]{32}$"
filePurgePeriodInMinutes: 1
genesysCallConversationLoggerTarget: "TargetTypeDB"
genesysCallEventDataMappingDefinition: "|1=ADagentid|2=ADextension|3=ADqueue|4=ADpassword|5=ADagentip|"
genesysCallEventLoggerTarget: "TargetTypeDB"
genesysConfigAgentSyncPeriodInMinutes: 30
genesysConfigServerLookupPeriodInMinutes: 30
genesysConfigServerPrimaryHost: "192.168.12.36"
genesysConfigServerPrimaryPort: 2020
genesysConversationDataMappingDefinition: "|1=ADagentid|2=ADextension|3=ADqueue|4=ADpassword|5=ADagentip|"
genesysCtiExecutionMode: "P"
genesysFailFullDirectoryName: "D:\\dump\\GenesysFail"
genesysMonitoredExtensionRange: "self.In( 1003, 142, 1621, 2010, 99550, test_agent_2\
  \ )"
genesysTelephonyServerPrimaryHost: "192.168.12.185"
genesysTelephonyServerPrimaryPort: 3100
genesysTelephonyServerRtpPassword: "{cipher}f244f0d713a8d27b2a22410a22565ee14265c005d7ae0e46e06c10e5bf808d69"
genesysTelephonyServerStandbyHost: "192.168.2.180"
genesysTelephonyServerStandbyPort: 3103
hazelcastAddresses: "localhost:5701"
instanceId: "Server001"
isActiveRecordingEnabled: true
isAddProjectIdToMediaPath: true
isAlcatelBipToneGenerationEnabled: true
isAlcatelConfigServerEnabled: false
isAlcatelCtiHighAvailabilityEnabled: false
isAlcatelTelephonyServerEnabled: true
isAlcatelTsapiEnabledandStartRecordingDisabled: false
isAllInOneConfiguration: false
isCTICheckEnabled: true
isCacheClearEnabled: true
isCallEventLogEnabled: false
isCompressionEnabled: true
isEnvironmentMetricsEnabled: true
isFilePurgeEnabled: false
isGenesysActiveRecordingEnabled: false
isGenesysConfigAgentSyncEnabled: true
isGenesysConfigServerEnabled: false
isGenesysForceCTIReregisterOnLookupPeriod: false
isGenesysLoggingEnabled: false
isGenesysTelephonyServerEnabled: true
isHazelcastEnabled: false
isImpersonationCachingEnabled: false
isMigrated: true
isRedisEnabled: false
isResourceListeningEnabled: true
isRestartProcessManagement: false
isScreenRecordingEnabled: true
isSistasConfigurationServerConfigUploadOnStartEnabled: true
isSistasConfigurationServerEnabled: true
isSkipCacheEnabled: false
managedCapturerClusterId: "Cluster001"
maxCacheExecutionActorCount: 3
maxCacheExecutionThreadCountPerActor: 1
maxCallCountInConversation: 9
mediaAttachmentTarget: "recorder"
metricsPublishingPeriodInSeconds: 61
minRemoveExpiredCallPartyContextInHours: 6
oAuth2ClientSecret: "{cipher}ae02fc2b2135cf602e29bfcc8e8c7418e08c3587c8aa777ef9d0d186b4d29f19969f81f661bb8063987ef37f4269c9ed710ae55040a2fb330ded38fa3f35000f"
prometheusHostname: "127.0.0.1"
prometheusPort: 28017
recorderMonitoredExtensionRange: "self.In( 1003, 142, 1621, 2010, 99550, test_agent_2\
  \ )"
recordingUserDataFilter: "!userData1.Contains(\"VRENABLED\")"
resourceListenBaseUri: "/SisBackupServer/BackupService/"
resourceListenHost: "127.0.0.1"
resourceListenPort: 28002
restAccessToken: "{cipher}f04366176555a0df08357eb7da30c355a7795d5cc217ebe6c7a9d1a1d8c55d14"
serviceRegisterRequestArgumentType: 11
sistasConfigurationServerDownloadPeriodInMinutes: 4
sistasConfigurationServerUrl: "http://192.168.2.70:8888"
statisticPeriod: 900003
voiceAdminHost: "127.0.0.1"
voiceAdminPort: 28015
webServerHost: "127.0.0.1"
webServerPort: 28005
